### ISSUE TITLE
Change default `form` parameter to 'logitnorm'

### ISSUE THREAD

**Issue by AngusMcLure** [AngusMcLure/PoolPoweR#17]
The logitnormal form for the cluster-level prevalence distribution, is more stable computationally so I think it should probably be the default. For small sigma (low correlation) it is very similar to beta distribution

**Comment by AngusMcLure** [comment]
Yeah, I think we can go ahead and make logitnorm the default. When I eventually extend the package so it works for multilevel sampling (clusters in clusters) then logitnorm and cloglognormal might be the first (and only) options I implement. The logitnormal also corresponds to the most common way people analyse these surveys (mixed effect logistic regression)

**Comment by fredjaya** [comment]
Cool, will do. 

Note to self: I think this will break a LOT of tests where `form=` was not specified i.e. `form="beta"` by default :) :)
