### ISSUE TITLE
multiple local function definitions for ‘integrand’

### ISSUE THREAD

**Issue by fredjaya** [AngusMcLure/PoolPoweR#21]
Currently the only note returned (no errors or warnings) when running R CMD check:
```
N  checking R code for possible problems (2.1s)
   fi_pool_cluster: multiple local function definitions for ‘integrand’
     with different formal arguments
```

Posting as an issue so I don't forget later

**Comment by AngusMcLure** [comment]
I solved this by having a different name for the integrand function for `form = xnorm`.  Closed with 564be51
